ICS_PROJECT/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from reviews import views as review_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
    path('about/', views.about),
    path('', review_views.review_list, name = "home" ),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
 

accounts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup_view, name = "signup"),
  path('login/', views.login_view, name = "login"),
  path('logout/', views.logout_view, name = "logout"),
]
 

reviews/urls.py
from django.urls import path, re_path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.review_list, name="list"),
    path('create/', views.review_create, name="create"),
    re_path(r'^(?P<slug>[\w-]+)/$', views.review_detail, name="detail"),
]
 

accounts/models.py
from django.db import models

# Create your models here.

reviews/models.py
from django.db import models
from django.contrib.auth.models import User

class review ( models.Model) :    #model is represented by a class in django, inherting Model from models class

    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author =  models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    bookAuth = models.CharField(max_length = 100)

    def __str__(self) : 
        return self.title 

    def snippet(self) :
        return self.body[:50] + " ..."   #takes first 50 char of the string

reviews/forms.py
from django import forms
from . import models

class Createreview(forms.ModelForm):
    class Meta:
        model = models.review
        fields = ['title', 'body', 'slug', 'thumb', 'bookAuth']

ICS_PROJECT/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homePage(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):       
    if request.method == 'POST' :
        form = UserCreationForm(request.POST)  
        if form.is_valid():
            user = form.save()  
            login(request, user)
            return redirect('reviews:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})


def login_view (request) : 
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log   in the user
            user = form.get_user() #to get user from form
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('reviews:list')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form':form})


def logout_view(request) : 
    if request.method == 'POST' :
        logout(request)
        return redirect ( 'reviews:list' )

reviews/views.py
from django.shortcuts import render,redirect
from .models import review
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def review_list (request) : 
    reviews = review.objects.all().order_by('date') #error faltu mien arha ha
    return render(request, 'reviews/review_list.html', {'reviews':reviews})


def review_detail(request, slug): 
    # return HttpResponse(slug)
    review_det = review.objects.get(slug=slug)
    return render(request, 'reviews/review_detail.html', {'review':review_det})



@login_required(login_url = "/accounts/login/") #protecting this user to login will first check if the user is logged in or not
def review_create(request) : 
    if request.method == 'POST':
        form = forms.Createreview(request.POST, request.FILES)
        if form.is_valid():
            #saving the review to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('reviews:list')
    else:
        form = forms.Createreview()
    return render(request, 'reviews/review_create.html', {'form':form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}


{% block content %}

    <h1>Login</h1>
    <br />
    <form action="{% url 'accounts:login' %}" class="site-form" method="POST">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
            <input type="submit" value="Login">
    </form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}


{% block content %}

    <h1>Signup</h1>

    <form class="site-form" action="/accounts/signup/" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>

{% endblock %}

reviews/templates/reviews/review_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-review">
        <h2> Upload a review! </h2>
        <form action="{% url 'reviews:create' %}" class="site-form" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create!">
        </form>
    </div>
    <footer>
        <p>
          Made By
          <span
            ><br />
            Abdullah
          </span>
          <span
            ><br />
            Ezan
          </span>
          <span
            ><br />
            Hassan
          </span>
          <span
            ><br />
            Shayan</span
          >
        </p>
      </footer>
    <script src="/static/slugify.js"></script>
{% endblock %}

reviews/templates/reviews/review_detail.html
{% extends 'base_layout.html' %}

{% block content%}
    <div class="review-detail">
        <div class="review">
            <img src="{{ review.thumb.url }}" alt="">
            <h2 class="book_title">{{ review.title }}</h2>
            <p class="book_author"> -{{ review.bookAuth }}</p>
            <p class="review_remarks"> {{ review.body }} </p>
            <h4 class="book_user">Review By : {{review.author}}</h4>
            <h5 class="review_date"> {{ review.date }}</h5>

        </div>
    </div>
    <footer>
        <p>
          Made By
          <span
            ><br />
            Abdullah
          </span>
          <span
            ><br />
            Ezan
          </span>
          <span
            ><br />
            Hassan
          </span>
          <span
            ><br />
            Shayan</span
          >
        </p>
      </footer>
{% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <div class="main">
        <div class="main-content">
            <h1 class="qoute">
                “ 
                <br />
                IF YOU DON'T LIKE TO <br>READ, YOU HAVE'NT<br>FOUND A RIGHT BOOK.
                <br/>
                ”
            </h1>
            <h3 class="name">
                -J.K Rowling
            </h3>
        </div>
    </div>
    <h1 class="book-heading">BOOK REVIEWS</h1>
    <div class="reviews">
        {% for review in reviews %}
            <div class="book-container">
                    <a href="{% url 'reviews:detail'  slug=review.slug %}"><img src={{review.thumb.url}} /></a>
                    <p class="book-title">{{review.title}}</p>
                    <p class="auth-name">-{{ review.bookAuth }}</p>
            </div>
        {% endfor %}
    </div>
    <footer>
        <p>
          Made By
          <span
            ><br />
            Abdullah Anis -- EB-20102003
          </span>
          <span
            ><br />
            Ezan Asif -- EB-20102027
          </span>
          <span
            ><br />
            Hassan Rasheed -- EB-20102079
          </span>
          <span
            ><br />
            Shayan Irfan -- EB-20102121</span
          >
        </p>
      </footer>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
</head>
<body>
    <footer>
        <p>
          Made By
          <span
            ><br />
            Abdullah
          </span>
          <span
            ><br />
            Ezan
          </span>
          <span
            ><br />
            Hassan
          </span>
          <span
            ><br />
            Shayan</span
          >
        </p>
      </footer>
</body>
</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Book Review App</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
  </head>
  <body>
    <header class="wrapper-1">
      <h1><a href="{% url 'home' %}">ICS PROJECT</a></h1>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <form action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="logout">Logout</button>
            </form>
          </li>
          <li>
            <a class="highlight" href="{% url 'reviews:create' %}"
              >Upload A Review
            </a>
          </li>
          {% else %}
          <li><a href="{% url 'accounts:login' %}" class="login">Login</a></li>
          <li>
            <a href="{% url 'accounts:signup' %}" class="signup">Signup</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <div class="wrapper">{% block content %} {% endblock %}</div>
  </body>
</html>

templates/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>ICS PROJECT</title>
</head>
<body>
    <h1>This is the homepage</h1>
    <footer>
        <p>
          Made By
          <span
            ><br />
            Abdullah
          </span>
          <span
            ><br />
            Ezan
          </span>
          <span
            ><br />
            Hassan
          </span>
          <span
            ><br />
            Shayan</span
          >
        </p>
      </footer>
</body>
</html>